"""Shared attribute sets used by multiple tool modules."""

from __future__ import annotations

USER_ATTRS = [
    "cn",
    "distinguishedName",
    "sAMAccountName",
    "userPrincipalName",
    "displayName",
    "givenName",
    "sn",
    "mail",
    "title",
    "department",
    "company",
    "manager",
    "telephoneNumber",
    "mobile",
    "physicalDeliveryOfficeName",
    "employeeID",
    "employeeType",
    "description",
    "userAccountControl",
    # Constructed: the only place AD reports lockout and password expiry.
    "msDS-User-Account-Control-Computed",
    "msDS-UserPasswordExpiryTimeComputed",
    "accountExpires",
    "pwdLastSet",
    "lastLogonTimestamp",
    "lastLogon",
    "badPwdCount",
    "badPasswordTime",
    "lockoutTime",
    "logonCount",
    "memberOf",
    "primaryGroupID",
    "objectSid",
    "objectGUID",
    "whenCreated",
    "whenChanged",
    "userWorkstations",
    "servicePrincipalName",
]

GROUP_ATTRS = [
    "cn",
    "distinguishedName",
    "sAMAccountName",
    "description",
    "groupType",
    "member",
    "memberOf",
    "managedBy",
    "info",
    "mail",
    "objectSid",
    "objectGUID",
    "whenCreated",
    "whenChanged",
]

OU_ATTRS = [
    "ou",
    "distinguishedName",
    "description",
    "gPLink",
    "gPOptions",
    "managedBy",
    "objectGUID",
    "whenCreated",
    "whenChanged",
]

COMPUTER_ATTRS = [
    "cn",
    "distinguishedName",
    "sAMAccountName",
    "dNSHostName",
    "operatingSystem",
    "operatingSystemVersion",
    "operatingSystemServicePack",
    "userAccountControl",
    "lastLogonTimestamp",
    "lastLogon",
    "pwdLastSet",
    "servicePrincipalName",
    "memberOf",
    "description",
    "location",
    "managedBy",
    "objectSid",
    "objectGUID",
    "whenCreated",
    "whenChanged",
]

GPO_ATTRS = [
    "cn",
    "displayName",
    "distinguishedName",
    "gPCFileSysPath",
    "gPCMachineExtensionNames",
    "gPCUserExtensionNames",
    "flags",
    "versionNumber",
    "objectGUID",
    "whenCreated",
    "whenChanged",
]

DOMAIN_ATTRS = [
    "distinguishedName",
    "name",
    "objectSid",
    "objectGUID",
    "maxPwdAge",
    "minPwdAge",
    "minPwdLength",
    "pwdHistoryLength",
    "pwdProperties",
    "lockoutDuration",
    "lockoutObservationWindow",
    "lockoutThreshold",
    "ms-DS-MachineAccountQuota",
    "msDS-Behavior-Version",
    "fSMORoleOwner",
    "whenCreated",
    "whenChanged",
]

TRUST_ATTRS = [
    "cn",
    "distinguishedName",
    "trustPartner",
    "trustType",
    "trustDirection",
    "trustAttributes",
    "flatName",
    "whenCreated",
    "whenChanged",
]
